version: "3"
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: --innodb-buffer-pool-size=500M --max_allowed_packet=32M
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}