# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/php:7.2-cli

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    - image: circleci/mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: my-secret-pw
        MYSQL_DATABASE: footie_testing
        MYSQL_USER: footie_user
        MYSQL_PASSWORD: footie_pw

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: composer install -n

    - save_cache:
        paths:
        - ./vendor
        key: v1-dependencies-{{ checksum "composer.json" }}

    # run tests!
    - run: ./bin/console doctrine:migrations:execute 20181026113305 -n
    - run: ./bin/console doctrine:fixtures:load -n
    - run: ./bin/phpunit